In [1]:
# SVM
# Support vector machines (SVMs) are a set of supervised learning methods used for 
# classification, regression and outliers detection.

# The advantages of support vector machines are:
    # Effective in high dimensional spaces.
    # Still effective in cases where number of dimensions is greater than the number of samples.
    # Uses a subset of training points in the decision function (called support vectors), 
    # so it is also memory efficient.
    # Versatile: different Kernel functions can be specified for the decision function. 
    # Common kernels are provided, but it is also possible to specify custom kernels.

# The disadvantages of support vector machines include:
    # If the number of features is much greater than the number of samples, avoid over-fitting 
    # in choosing Kernel functions and regularization term is crucial.
    # SVMs do not directly provide probability estimates, these are calculated using an 
    # expensive five-fold cross-validation (see Scores and probabilities, below).

# class sklearn.svm.SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', 
# coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, 
# class_weight=None, verbose=False, max_iter=-1, 
# decision_function_shape='ovr', break_ties=False, random_state=None)

from sklearn import svm
import pandas as pd
import numpy as np

np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [4]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# data
fruits = pd.read_csv('NHANES_data_stroke_train.csv')

#under sample the non-stroke
MI_positive = fruits[fruits['stroke'] == 1]
MI_negitive = fruits[fruits['stroke'] == 2].sample(frac=.03411675511751327)
fruits = pd.concat([MI_positive, MI_negitive])

#
fruit_featureNames = ["Income","Sex","Age","Race","Edu","Diastolic","Systolic","Pulse","BMI","HDL","Trig","LDL","TCHOL","kidneys_eGFR","Diabetes","CurrentSmoker","isActive","isInsured"]
X = fruits[["Income","Sex","Age","Race","Edu","Diastolic","Systolic","Pulse","BMI","HDL","Trig","LDL","TCHOL","kidneys_eGFR","Diabetes","CurrentSmoker","isActive","isInsured"]]
y = fruits['stroke']

# Define the preprocessing pipeline
preprocessing_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),  # Impute missing values
    ('scaler', StandardScaler())  # Scale the features
])

# Fit and transform the preprocessing pipeline
X = preprocessing_pipeline.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.50, random_state=42)

# kernals could be: ‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’.              
clf = svm.SVC(kernel="linear", C=1000, probability=True)

clf.fit(X_train, y_train)
print("accuracy train : ", clf.score(X_train, y_train))
print("accuracy test : ", clf.score(X_test, y_test))

print("predicted probabilities:\n", clf.predict_proba(X_test))

##############################  PREDICIOTN  ##############################################
# load data set
new_data = pd.read_csv("DEMO.csv")

# No stroke column so get rid of it
new_data = new_data.drop(columns=['stroke'])

# get attributes
X_new = new_data[fruit_featureNames]

# imputer
X_new = preprocessing_pipeline.fit_transform(X_new)

# Make predictions on the new data, run model
new_probabilities = clf.predict_proba(X_new)[:, 0]  # for output
new_predictions = clf.predict(X_new) # unsed, just for testing ratio of MI/noMI

# Get each sample's ID and write probabilities to the output CSV
new_participant_ids = new_data['SEQN']
new_output_df = pd.DataFrame({'SEQN': new_participant_ids, 'Pred_Probability': new_probabilities})
new_output_df.to_csv('SVMpred.csv', index=False)


accuracy train :  0.837037037037037
accuracy test :  0.6666666666666666
predicted probabilities:
 [[0.744 0.256]
 [0.485 0.515]
 [0.169 0.831]
 [0.437 0.563]
 [0.191 0.809]
 [0.128 0.872]
 [0.237 0.763]
 [0.525 0.475]
 [0.629 0.371]
 [0.649 0.351]
 [0.122 0.878]
 [0.301 0.699]
 [0.391 0.609]
 [0.862 0.138]
 [0.107 0.893]
 [0.538 0.462]
 [0.145 0.855]
 [0.095 0.905]
 [0.390 0.610]
 [0.584 0.416]
 [0.109 0.891]
 [0.869 0.131]
 [0.827 0.173]
 [0.517 0.483]
 [0.168 0.832]
 [0.900 0.100]
 [0.566 0.434]
 [0.691 0.309]
 [0.840 0.160]
 [0.831 0.169]
 [0.695 0.305]
 [0.551 0.449]
 [0.468 0.532]
 [0.579 0.421]
 [0.500 0.500]
 [0.584 0.416]
 [0.778 0.222]
 [0.518 0.482]
 [0.367 0.633]
 [0.220 0.780]
 [0.878 0.122]
 [0.271 0.729]
 [0.524 0.476]
 [0.298 0.702]
 [0.743 0.257]
 [0.042 0.958]
 [0.378 0.622]
 [0.384 0.616]
 [0.818 0.182]
 [0.390 0.610]
 [0.109 0.891]
 [0.223 0.777]
 [0.441 0.559]
 [0.922 0.078]
 [0.783 0.217]
 [0.287 0.713]
 [0.312 0.688]
 [0.174 0.826]
 [0.135 0.865]
 [0.293 0.707]
 [

In [4]:
#### See which data points are critical #####
# get the support vectors
print("clf support vectors: {}".format(clf.support_vectors_))
# get indices of support vectors
print("clf support vector indices: {}".format(clf.support_))
# get number of support vectors for each class
print("clf # of support vectors in each class: {}".format(clf.n_support_))

clf support vectors: [[-1.125 -1.015 1.225 ... 0.557 0.540 -0.348]
 [0.000 0.985 -0.495 ... -1.794 0.540 -0.348]
 [-0.943 0.985 -1.068 ... 0.557 0.540 -0.348]
 ...
 [0.074 0.985 0.733 ... 0.557 0.540 -0.348]
 [-0.155 0.985 -0.086 ... -1.794 0.540 -0.348]
 [-0.903 -1.015 0.570 ... 0.557 0.540 2.882]]
clf support vector indices: [  0  13  14  15  19  22  24  32  34  37  39  40  43  46  52  53  57  61
  62  63  64  67  74  81  82  85  88  89  93  97  99 100 110 112 113 115
 123 125 132 133 134   2   3   5   6  12  16  17  31  38  41  42  45  48
  51  58  59  60  66  73  75  76  77  87  92  94 103 106 108 109 118 119
 121 122 124 127 129]
clf # of support vectors in each class: [41 36]
